# See `linux.toml` for more settings to add on Windows

# Windows settings
[nvim.files]
nvim = "~/AppData/Local/nvim"

[yazi.files]
yazi = "~/AppData/yazi/config"

[helix.files]
helix = "~/AppData/Roaming/helix"

[yasb.files]
yasb = "~/.config/yasb"

[komorebi.files]
komorebi = "~/"

[whkd.files]
whkd = "~/.config"

[wezterm.files]
wezterm = "~"