# See `linux.toml` for more settings to add on Windows

# Windows settings
[nvim.files]
nvim = "~/AppData/Local/nvim"

[yazi.files]
yazi = "~/AppData/yazi/config"

[helix.files]
helix = "~/AppData/Roaming/helix"
