[zsh.files]
"zsh/.zshrc" = "~/.zshrc"

[helix.files]
helix = "~/.config/helix"

[zed.files]
zed = "~/.config/zed"

[yazi.files]
yazi = "~/.config/yazi"

[powershell.files]
"powershell/Microsoft.PowerShell_profile.ps1" = "~/.config/powershell/Microsoft.PowerShell_profile.ps1"
